### ISSUE TITLE
 PermissionError

### ISSUE THREAD

**Issue by fadiga** [yeleman/ramed-desktop#1]
[WinError 32] Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus: Path('C:\Users\fadiga\Desktop\Données Collecte\PDF')

**Comment by rgaudin** [comment]
tentative d'ecriture ou suppression d'un fichier (PDF) ouvert.
Lors de l'annulation d'un export, il essaie de supprimer les fichiers.

À voir ce qu'on veut faire dans ces cas là
